### ISSUE TITLE
Missing trips

### ISSUE THREAD

**Issue by mvexel** [openstreetview/openstreetview.org#1]
There seem to be trips missing from the new map overlay. Here is what one of our beta testers reported:

> Hi Martin I've noticed you updated the website, but there are a lot of tracks missing(and yes I cleared my cache), I've waited a long time and they still dont show up. Is this because you are reprocessing the files that have been processed to match them to the roads as you said in the beta news letter?
> 
> Example what's highlighted in yellow should have imagery(from what I recall and a quick pass over) :
> 

![image](https://cloud.githubusercontent.com/assets/120452/17026062/fe3b510e-4f1b-11e6-8a43-2db3ca2c27a7.png)

**Comment by MikeTho16** [comment]
I am seeing this same thing (user: tekim).  I uploaded a sequence nearly 24 hours ago and it is not showing up.

**Comment by james2432** [comment]
Also sometimes they do appear but only partially, see highlighted areas
![partials](https://cloud.githubusercontent.com/assets/498547/17276583/48fca670-56e2-11e6-8f6e-95df093005d6.PNG)

**Comment by Xevib** [comment]
Same for me, in my case this track http://openstreetview.org/details/10400/1

**Comment by james2432** [comment]
There's also roads that say I've passed on like this track: http://openstreetview.com/details/8745
![didnot](https://cloud.githubusercontent.com/assets/498547/17348307/7428cb64-58e3-11e6-839c-d8c26597dbac.PNG)
The road surrounded in red is a place I did not pass, but the website says I did (and I doubt any other people drove there)

**Comment by martijnv-telenav** [comment]
I think the missing trips were the result of initial catching up that the production server needed to do. Closing this now but feel free to file a new bug or add your experience to #35 or #36
