### ISSUE TITLE
Distance on the leaderboard is wrong

### ISSUE THREAD

**Issue by Xevib** [openstreetview/openstreetview.org#17]
I supose that are meters instead of km. The same passes on the distance that appears on the profile 

![image](https://cloud.githubusercontent.com/assets/2422305/17179308/0429bd7e-5419-11e6-9de5-686a9478e118.png)

**Comment by james2432** [comment]
no those are indeed KM, telenavdrives are commercial drivers telenav hired to do big drives

**Comment by martijnv-telenav** [comment]
James, `telenavdrives` are **test drives** we do internally.

**Comment by Xevib** [comment]
@james2432 I'm the third on the list and I'm sure that I don't did so much KM

**Comment by james2432** [comment]
@Xevib seems you are rank 50 now with 154.51 km

**Comment by Xevib** [comment]
@james2432 now it seems more real

**Comment by Xevib** [comment]
I think that is fixed
