### ISSUE TITLE
Android App Crashes

### ISSUE THREAD

**Issue by MikeTho16** [openstreetview/openstreetview.org#18]
I have had about six cases where the Android app crashes. I have a Samsung S3 with Android version 4.4.2. This happened twice on my way to work this morning which is about a 1/2 hour, 15 mile drive. The app shut down after about five to 10 minutes of recording.  It also happened a couple of times while walking with the app after only a few photos were taken.

**Comment by mvexel** [comment]
Hi @MikeTho16, 

Sorry you are experiencing crashes. These are logged automatically. So we should be able to act on those as they come in. Thanks for reporting and being specific around device model and Android version.

**Comment by MikeTho16** [comment]
Martijn Thanks for the response. Let me know if there is any specific testing I can do to help you track this down.  My OSV username is tekim.

**Comment by kalmanbencze** [comment]
Hi MikeTho16, could you tell us if you saw the typical "app has crashed" popup, or did the app restart shortly after the crash? Thanks.

**Comment by MikeTho16** [comment]
@kalmanbencze Most of the time it simply exits without a message.  Sometimes there is a popup stating that the app has crashed (next time it happens I will attempt to write down the exact wording) and asking if I would like to report it.  I usually click yes, but I think a couple times in my haste I clicked the other option.  The app stopped (with no message) three times on my way to work this morning.  Also, it crashed - with a popup - last night while uploading photos, although I think all photos were uploaded.

**Comment by james2432** [comment]
This bug report should probably be moved to the android repo @mvexel

**Comment by kalmanbencze** [comment]
This issue was moved to openstreetview/android#9
