### ISSUE TITLE
Delete Account button, possible account deletion by accident

### ISSUE THREAD

**Issue by james2432** [openstreetview/openstreetview.org#2]
When clicking on the account:
![capture](https://cloud.githubusercontent.com/assets/498547/17032034/331dafa6-4f45-11e6-9578-2b916e62ba11.PNG)
The delete button is right underneath it which could be dangerous if clicking more than once:
![capture2](https://cloud.githubusercontent.com/assets/498547/17032058/5bbaf9f0-4f45-11e6-8cec-c9898e3163c8.PNG)

My browser was:
Browser window width:	1317px
Browser window height:	619px

**Comment by james2432** [comment]
closing as you seemed to have fixed it on website by removing it completely from that location

**Comment by shiba89** [comment]
So is there now some way to delete an account?
