### ISSUE TITLE
some comments

### ISSUE THREAD

**Issue by iagsav** [openstreetview/openstreetview.org#20]
1. very slow data uploading
2. irritating popup message on starting / stopping the download
3. frequent Android application crashig

**Comment by martijnv-telenav** [comment]
1. how slow, and how fast would you expect it to be? what speed the maximum you get when uploading to other sites on the same connection?
2. Which download are you referring to and from what source?
3. Crashes are logged automatically and will be looked into.

**Comment by iagsav** [comment]
1.  The fastet = slowest = 15 KB/S. My speed to another sites for about 2 MB/s
2. My message was incorrect, I mean "uploading" and the message in the bottom of the screen

**Comment by martijnv-telenav** [comment]
1. That's definitely abnormally slow. It could be a temporary thing. Can you report back if it continues to be slow? Where do you upload from (country)?
2. Okay, noted.

**Comment by iagsav** [comment]
I can report about it, if it continues (Russia)

**Comment by james2432** [comment]
I have 2.4Mbps upload on crappy hotel connections, I dont't think it's slow(Canada)

**Comment by iagsav** [comment]
@james2432 you have same problems?

**Comment by james2432** [comment]
![capture666](https://cloud.githubusercontent.com/assets/498547/17215611/4ea78786-5492-11e6-97f3-59fb35bd6609.PNG)
No my upload goes pretty quickly (all bandwidth is currently being used by upload script)
Also have no issues with phone

**Comment by martijnv-telenav** [comment]
This issue was moved to openstreetview/android#4
