### ISSUE TITLE
Android app isn't on F-Droid

### ISSUE THREAD

**Issue by redsteakraw** [openstreetview/openstreetview.org#22]
[F-Droid](https://f-droid.org) is the free software app store for android, it is a collection of various open source apps including many OpenStreetMap apps. I would love to be able to download and use the app from F-Droid.  

https://f-droid.org

**Comment by kalmanbencze** [comment]
We will look into it, most probably will release on F-droid as well.

**Comment by james2432** [comment]
Should probably be moved to android repo @martijnv-telenav

**Comment by kalmanbencze** [comment]
This issue was moved to openstreetview/android#8
