### ISSUE TITLE
Images are Mirrored 

### ISSUE THREAD

**Issue by MikeTho16** [openstreetview/openstreetview.org#23]
The images in my latest upload are mirrored (i.e. what is on the left in reality is on the right in the image and vise versa, for example: [http://openstreetview.org/details/10557/14](url). Thus, it appears as if I was driving on the left (wrong side in US), when in fact I was driving on the right and words on signs and on the pavement also appear backwards.

**Comment by kalmanbencze** [comment]
Hello, could you tell us what device did you use? Thanks.

**Comment by MikeTho16** [comment]
@kalmanbencze Samsung Galaxy S3 running Android 4.4.2. I should note that it doesn't always produce mirrored images, only sometimes.

**Comment by martijnv-telenav** [comment]
This issue was moved to openstreetview/android#3
