### ISSUE TITLE
Filter date has no effect on tracks list [metrics.openstreetview.com]

### ISSUE THREAD

**Issue by james2432** [openstreetview/openstreetview.org#28]
The track list isn't filtered by the start/end date filter. It's only affected by the userlist filter(as it only shows when a user is selected under the graph). It will show all the tracks a user has uploaded over the life of their account.

**Comment by alexandrui-telenav** [comment]
Hi @james2432, the metrics page is for internal usage for now, how did you even found that? 😄

**Comment by james2432** [comment]
I'm a beta member, Martin had sent it in an email to the beta users. Also I like to break things to make em better, so that's how I found that bug

**Comment by martijnv-telenav** [comment]
Closing this now, this metrics page is not part of the official OSV platform :)
