### ISSUE TITLE
Picutres out of order in trace

### ISSUE THREAD

**Issue by ToeBee** [openstreetview/openstreetview.org#33]
I noticed that my most recent uploads had a ridiculously high number of kilometers listed. It turns out the images are out of order on the server so the trace is going back and forth all over the countryside and racking up hundreds of kilometers in a hurry.

How are you ordering the images? This might be an uploader issue rather than the server... I'm not sure. Example trace: http://openstreetview.com/details/11171/49

**Comment by ToeBee** [comment]
I guess for completeness I'll add the other two traces I've seen this on:
http://openstreetview.com/details/11173/0
http://openstreetview.com/details/11174/1

I'ts just my 3 most recent uploads. I don't know why these pictures would be different than others I have uploaded. They're all from my GoPro camera and externally geotagged with the same tools as all my other pictures.

**Comment by ToeBee** [comment]
After tinkering a bit more, it seems like you are relying on the upload timestamp to determine picture order in the sequence? ... with a multi-threaded upload script. Does anyone else see a problem here? :)

Also, the upload script is ordering the files by file system mtime. Depending on how I pull pictures off of the camera or what pre-processing I've done before uploading, the file modification time may or may not reflect the actual order of the pictures.

I think you really need to rely on the EXIF timestamp to order the sequence after an upload has been completed.

**Comment by james2432** [comment]
mtime is not affected by copying. Only if you modify the picture in photoshop or paint will it affect the mtime. Creation time is not reliable as copying affects it.

**Comment by ToeBee** [comment]
> Only if you modify the picture in photoshop or paint will it affect the mtime

Or a geotagging script. All 800 of the pictures in one of the traces I linked above have an `mtime` value within a few seconds of each other because the geotagging script wrote the GPX EXIF tags to all of them in a matter of seconds. This leads to a lot of them having **identical** mtimes:

    $ stat G002557*.JPG | grep Modify
    Modify: 2016-05-30 22:17:24.000000000 -0500
    Modify: 2016-05-30 22:17:24.000000000 -0500
    Modify: 2016-05-30 22:17:24.000000000 -0500
    Modify: 2016-05-30 22:17:24.000000000 -0500
    Modify: 2016-05-30 22:17:24.000000000 -0500
    Modify: 2016-05-30 22:17:24.000000000 -0500
    Modify: 2016-05-30 22:17:24.000000000 -0500
    Modify: 2016-05-30 22:17:24.000000000 -0500
    Modify: 2016-05-30 22:17:24.000000000 -0500
    Modify: 2016-05-30 22:17:24.000000000 -0500

I'm not sure what python will do with this when you tell it to sort by mtime. I'm guessing it defaults to the order that the file list is returned by the underlying OS and file system which can not be relied on for order or repeatability. So I think mtime is out as a sorting key.

**Comment by ToeBee** [comment]
Oh and I don't know if anyone was going to try to fix the broken ones I linked to above but no need to do that. I have already re-uploaded these pictures after modifying the script to sort by file name which in the case of my GoPro pictures is the easiest way to put them in chronological order. Once this issue is resolved I will just delete the broken ones.

**Comment by james2432** [comment]
Sorting by name is how they were sorting before, but it's worse as python doesn't sort names properly ex it would sort files like this:

VIRB100.jpg VIRB100-10.jpg VIRB100-12.jpg VIRB100-13.jpg VIRB100-14.jpg VIRB100-15.jpg VIRB100-16.jpg VIRB100-17.jpg VIRB100-18.jpg VIRB100-19.jpg  VIRB100-2.jpg VIRB100-20.jpg  VIRB100-21.jpg .... etc

**Comment by ToeBee** [comment]
Yeah I figured sorting by name might not work for all cameras. I'm kind of curious though. What pictures don't have an EXIF timestamp? I mean you require GPS EXIF info to upload. Are there cameras out there that set the GPS info but not the timestamp?

Maybe there needs to be a fall-back order? Use EXIF time to order on the server if available but if not, fall back to something else?

Also, can you confirm or deny that the ordering is actually happening by the order the images are received on the server? I've been forcing the upload script to run with only 1 thread for fear of more ordering problems.

**Comment by james2432** [comment]
Seems to happen via how the files are ordered on upload, they are assigned an index number and is passed during the POST
![sequence](https://cloud.githubusercontent.com/assets/498547/17411820/cbdbaab0-5a47-11e6-8436-e6068a36667c.PNG)

**Comment by martijnv-telenav** [comment]
Thanks for digging into this a bit guys... It looks to me to be an uploader issue, @bogdan-telenav or if it's back end @alexandrui-telenav should be able to get someone to look into it.

**Comment by james2432** [comment]
back-end would probably be best as relying on client side sorting is not a super great method. Server in the processing stage should be able to reorder the sequence index based on DATETIME ORIGINAL exif tag. As  ToeBee said doubt any camera will not include this tag, but if people assign gps locations to non-exif'd images, might cause issues.

**Comment by ToeBee** [comment]
Ah ok so threading is safe after all. I tried uploading one of the sequences several times while tweaking the script a little and thought I saw some variation in the picture order that wasn't due to my changes. This made me think that the threading might be involved as well. Good to know this isn't the case. Time to go max out some more bandwidth :)

**Comment by alexandrui-telenav** [comment]
Wow, you guys really delved into this. As you suggested the exif tag should be the way to go, optionally fallback to filename maybe? 
@james2432 can you elaborate why client side ordering would not be a good idea?

**Comment by james2432** [comment]
@alexandrui-telenav I was thinking in terms of performance of upload, having to open each file to get the date stamp then ordering the list. Basing sequence order shouldn't really be based on what order you upload them. The final metadata should be calculated after the upload is done

**Comment by marcgemis** [comment]
Fallback on filename might not always work. On my DSLR, files are numbered up to DSC_9999.jpg and then roll over to DSC_0000.jpg

**Comment by james2432** [comment]
I think all cameras roll over at 9999

**Comment by ToeBee** [comment]
Looks like this has been fixed over in the uploader repository by sorting by EXIF timestamp.
