### ISSUE TITLE
Login to http://openstreetview.org/

### ISSUE THREAD

**Issue by iagsav** [openstreetview/openstreetview.org#34]
Every time I go to a website I have to enter their credentials to log in to your profile. The accounting data is reset when you close the browser

**Comment by ToeBee** [comment]
Is this a duplicate of #13?

**Comment by iagsav** [comment]
Hello! i think it is similar but not the same

**Comment by james2432** [comment]
it's a duplicate, the reason you have to log in every time is because the oauth token is dropped

**Comment by alexandrui-telenav** [comment]
hi @ToeBee , appreciate you reported this. It's something we'll tackle in the current sprint so hopefully by the end of next week will be fixed.

**Comment by martijnv-telenav** [comment]
Closing as duplicate of #13
