### ISSUE TITLE
No binding to pathways [cycle, pedestrian, etc]

### ISSUE THREAD

**Issue by james2432** [openstreetview/openstreetview.org#46]
Example: http://openstreetview.com/details/9577/251 is a bike path and is a segment in OSM, but the openstreetview site it will only stop at the roadway:
http://openstreetview.com/map/@45.489084177296014,-75.51935166120528,18z

**Comment by ToeBee** [comment]
Similar to #38?

**Comment by james2432** [comment]
True it seems the same
