### ISSUE TITLE
Time Lapse

### ISSUE THREAD

**Issue by krl0z-cor3** [openstreetview/openstreetview.org#51]
se pudiera agregar un time lapse para que tome fotos cada ciertos segundos? sería mas fácil en el momento de grabar la pista en el auto o incluso en bicicleta

..............

You could add a lapse time to take pictures every few seconds? It would be easier in time to record the track in the car or even by bike

**Comment by james2432** [comment]
The app automatically adjusts to the speed you move. I believe it takes a picture every 4m you move or so. Taking timelapses is less efficient as when you are stopped, there are a lot of the same image

**Comment by krl0z-cor3** [comment]
lo digo porque he recorrido una pista y no captura fotografias si no le doy click, o no se si sea un error en mi celular

.................

I say this because I have not traveled a track and capture photographs if not give click, or not if it is an error on my cell

**Comment by bogdans-telenav** [comment]
@krl0z-cor3 what app are you using? iOS or Android? What device? What OS version?

**Comment by krl0z-cor3** [comment]
ya solucione el error, fue un problema con mi celular, ya pude cargar de manera correcta, cerrare el tema .... Gracias

................

I corrected the error was a problem with my phone, and I could load properly, I close the issue .... Thanks
