### ISSUE TITLE
Lost Sequences when website down

### ISSUE THREAD

**Issue by james2432** [openstreetview/openstreetview.org#62]
The website went down between 11:32am and 11:36am (GMT-5) and I was uploading to the website, every track that I uploaded during the downtime does not show up on my profile, I had to reset and re-upload and now they are there.
*edit*
I looked at the sequence id and it gave me -1, were you updating the services?

**Comment by bogdans-telenav** [comment]
@james2432 we had about 30 minutes of down time due to some migration of data to a new server. So most probably you tried to upload your data in that window frame and it did not work.

**Comment by james2432** [comment]
Thanks!
