### ISSUE TITLE
How do you upload Action Camera photos?

### ISSUE THREAD

**Issue by smsm1** [openstreetview/openstreetview.org#7]
There doesn't seem to be any documentation on how to upload action camera photos. I've have lots (hundreds of GBs) that I could upload.

**Comment by james2432** [comment]
In the beta they had a python script to do so and were working on a GUI, I'm sure they will release it to the public soon.

**Comment by bogdans-telenav** [comment]
@smsm1 as @james2432 said we have some scripts for doing exactly this also we are working on a GUI and they will be public in a few days.

**Comment by bogdan-telenav** [comment]
@smsm1 @yopaseopor Use python script to upload. You will find the scripts in repo: https://github.com/openstreetview/uploader
For action camera use upload_photos_by_exif
