### ISSUE TITLE
Improve offline support

### ISSUE THREAD

**Issue by JesseKPhillips** [openstreetview/openstreetview.org#82]
I use a prepaid phone and no data. It does not appear this app supports creating tracks and photos without data. I would like to be able to contribute through Wifi when my trip is complete.

**Comment by alexandrui-telenav** [comment]
Hi @JesseKPhillips , the app should definitely be able to record offline. I recently came back from a trip outside my country and that was how I recorded, then upload on the Wi-Fi. Are you using iOS or Android? When you say it's not creating tracks what do you see exactly in the app?
Thanks!

**Comment by james2432** [comment]
Maybe he's confusing viewing the map as blank as not being able to record?

**Comment by JesseKPhillips** [comment]
Hi, I'm using the Android app. It looks like this isn't related to being offline and instead it isn't working with my phone. The problem I'm seeing starts when I click the record button from the camera view. During record it presents a black screen with a minimap, as I drive the black screen will "flash" and a blue mark added to the map. During the entire trip none of the stats change (photo count, track distance, etc). Thank you for your time.
