### ISSUE TITLE
Manual picture upload

### ISSUE THREAD

**Issue by gzin** [openstreetview/openstreetview.org#84]
I can't find the button for a manual picture upload. Where is it?

I would like to upload some geocoded pictures (contribute to OSV and also to Mapillary).

When I login at OSV with my OSM account and change to "profile" there ist only a text "Upload tracks" but no button for that. Is it possible to upload only geocoded pictures without a matching GPX file?

Thx in advance.

**Comment by james2432** [comment]
I've made a GUI application that allows you to upload geotagged images(and remove duplicates: i.e. stopped at a stop light) in another project if you would like: https://github.com/osmottawa/OSVUploadr/releases

It doesnt upload pictures taken from OSV app yet but works with geotagged images, much like the python scripts available here.

**Comment by gzin** [comment]
Thank you for the quick response.
I've tried the python script: too many dependencies I could not resolve for now.
I've tried the java app: very nice idea, but I had some problems:
* I tried automated authentication: the file access_token.txt was empty and the response was:
Okt 05, 2016 7:52:39 PM ca.osmcanada.osvuploadr.JPMain Upload_Image<br/>
FATAL: null<br/>
java.io.IOException: Server returned HTTP response code: 400 for URL: http://openstreetview.com/1.0/photo/<br/>
...<br/>
Uploaded

What has happened? Was the photo deleted after the error?

* then I deleted the file access_token.txt and tried to authenticate manually. Then the file was 40 Bytes big, but the result was also:
Okt 05, 2016 8:39:33 PM ca.osmcanada.osvuploadr.JPMain Upload_Image<br/>
FATAL: null<br/>
java.io.IOException: Server returned HTTP response code: 500 for URL: http://openstreetview.com/1.0/photo/<br/>
...<br/>
Uploaded

The photo also was deleted after the error. What a pity.

What was wrong?

**Comment by james2432** [comment]
Does the sequence file (in photo folder) already have a number inside? (if it's -1 it would explain why it failed). Also java and python scripts work in the same manner.

**Comment by gzin** [comment]
Hi!

My files look like this:
2016_09_10_09_33_01_666.jpg
2016_09_10_09_33_02_913.jpg
2016_09_10_09_33_04_197.jpg
2016_09_10_09_33_05_185.jpg
2016_09_10_09_33_05_902.jpg
2016_09_10_09_33_06_685.jpg
2016_09_10_09_33_07_513.jpg
2016_09_10_09_33_08_324.jpg
2016_09_10_09_33_09_320.jpg
2016_09_10_09_33_10_297.jpg
Should I rename them?

I'm using Ubuntu 16.04 with Python 3.5.2.
I'm getting a step closer...
...there are still problems (with "jpeg"):

root@lapgz3:~# python3 -m pip install -r /home/gz/Download/GPS/OSV/requirements.txt
Collecting Pillow==3.1.1 (from -r /home/gz/Download/GPS/OSV/requirements.txt (line 1))
  Using cached Pillow-3.1.1.zip
Collecting rauth==0.7.2 (from -r /home/gz/Download/GPS/OSV/requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): requests==2.9.1 in /usr/lib/python3/dist-packages (from -r /home/gz/Download/GPS/OSV/requirements.txt (line 3))
Collecting image==1.4.4 (from -r /home/gz/Download/GPS/OSV/requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): six==1.10.0 in /usr/lib/python3/dist-packages (from -r /home/gz/Download/GPS/OSV/requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): ExifRead==2.1.2 in /usr/lib/python3/dist-packages (from -r /home/gz/Download/GPS/OSV/requirements.txt (line 6))
Collecting django (from image==1.4.4->-r /home/gz/Download/GPS/OSV/requirements.txt (line 4))
  Using cached Django-1.10.2-py2.py3-none-any.whl
Building wheels for collected packages: Pillow
  Running setup.py bdist_wheel for Pillow ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-7wgfk62t/Pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpjds5c04upip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.5
  creating build/lib.linux-x86_64-3.5/PIL
  copying PIL/features.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/ImageGrab.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/TiffTags.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/PcfFontFile.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/PngImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/ImageQt.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/PcdImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/ImageCms.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/BufrStubImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/PsdImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/EpsImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/SunImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/ImageStat.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/PpmImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/TiffImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/FitsStubImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/PSDraw.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/ImageColor.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/PcxImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/PaletteFile.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/BmpImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/XVThumbImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/_binary.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/ImageTk.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/ImagePalette.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/MpoImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/IcoImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/JpegPresets.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/IptcImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/ImagePath.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/ImageMorph.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/FontFile.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/TarIO.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/PixarImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/SpiderImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/ImageFile.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/PyAccess.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/FpxImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/IcnsImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/GdImageFile.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/ImageDraw2.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/Jpeg2KImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/ImageMath.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/GimpPaletteFile.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/ImageShow.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/ImageFont.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/ImageMode.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/XpmImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/MicImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/FliImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/ImImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/ImtImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/DcxImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/GifImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/ImageChops.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/Hdf5StubImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/PalmImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/WalImageFile.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/JpegImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/WebPImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/Image.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/GimpGradientFile.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/ContainerIO.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/GbrImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/_util.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/ImageWin.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/ImageTransform.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/MspImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/ImageFilter.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/ImageDraw.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/ImageSequence.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/TgaImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/GribStubImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/SgiImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/ExifTags.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/ImageEnhance.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/MpegImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/McIdasImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/CurImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/BdfFontFile.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/WmfImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/OleFileIO.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/XbmImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/PdfImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/ImageOps.py -> build/lib.linux-x86_64-3.5/PIL
  copying PIL/__init__.py -> build/lib.linux-x86_64-3.5/PIL
  running egg_info
  writing Pillow.egg-info/PKG-INFO
  writing top-level names to Pillow.egg-info/top_level.txt
  writing dependency_links to Pillow.egg-info/dependency_links.txt
  warning: manifest_maker: standard file '-c' not found
  
  reading manifest file 'Pillow.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files found matching '.editorconfig'
  writing manifest file 'Pillow.egg-info/SOURCES.txt'
  copying PIL/OleFileIO-README.md -> build/lib.linux-x86_64-3.5/PIL
  running build_ext
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-7wgfk62t/Pillow/setup.py", line 767, in <module>
      zip_safe=not debug_build(),
    File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 179, in run
      self.run_command('build')
    File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.5/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.5/distutils/command/build_ext.py", line 338, in run
      self.build_extensions()
    File "/tmp/pip-build-7wgfk62t/Pillow/setup.py", line 516, in build_extensions
      (f, f))
  ValueError: jpeg is required unless explicitly disabled using --disable-jpeg, aborting
  
  ----------------------------------------
  Failed building wheel for Pillow
  Running setup.py clean for Pillow
Failed to build Pillow
Installing collected packages: Pillow, rauth, django, image
  Found existing installation: Pillow 3.1.2
    Uninstalling Pillow-3.1.2:
      Successfully uninstalled Pillow-3.1.2
  Running setup.py install for Pillow ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-7wgfk62t/Pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-7y9wo3n8-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.5
    creating build/lib.linux-x86_64-3.5/PIL
    copying PIL/features.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/ImageGrab.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/TiffTags.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/PcfFontFile.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/PngImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/ImageQt.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/PcdImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/ImageCms.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/BufrStubImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/PsdImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/EpsImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/SunImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/ImageStat.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/PpmImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/TiffImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/FitsStubImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/PSDraw.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/ImageColor.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/PcxImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/PaletteFile.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/BmpImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/XVThumbImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/_binary.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/ImageTk.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/ImagePalette.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/MpoImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/IcoImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/JpegPresets.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/IptcImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/ImagePath.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/ImageMorph.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/FontFile.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/TarIO.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/PixarImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/SpiderImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/ImageFile.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/PyAccess.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/FpxImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/IcnsImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/GdImageFile.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/ImageDraw2.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/Jpeg2KImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/ImageMath.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/GimpPaletteFile.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/ImageShow.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/ImageFont.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/ImageMode.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/XpmImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/MicImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/FliImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/ImImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/ImtImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/DcxImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/GifImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/ImageChops.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/Hdf5StubImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/PalmImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/WalImageFile.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/JpegImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/WebPImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/Image.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/GimpGradientFile.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/ContainerIO.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/GbrImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/_util.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/ImageWin.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/ImageTransform.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/MspImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/ImageFilter.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/ImageDraw.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/ImageSequence.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/TgaImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/GribStubImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/SgiImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/ExifTags.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/ImageEnhance.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/MpegImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/McIdasImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/CurImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/BdfFontFile.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/WmfImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/OleFileIO.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/XbmImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/PdfImagePlugin.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/ImageOps.py -> build/lib.linux-x86_64-3.5/PIL
    copying PIL/__init__.py -> build/lib.linux-x86_64-3.5/PIL
    running egg_info
    writing Pillow.egg-info/PKG-INFO
    writing dependency_links to Pillow.egg-info/dependency_links.txt
    writing top-level names to Pillow.egg-info/top_level.txt
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'Pillow.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files found matching '.editorconfig'
    writing manifest file 'Pillow.egg-info/SOURCES.txt'
    copying PIL/OleFileIO-README.md -> build/lib.linux-x86_64-3.5/PIL
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-7wgfk62t/Pillow/setup.py", line 767, in <module>
        zip_safe=not debug_build(),
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.5/distutils/command/install.py", line 583, in run
        self.run_command('build')
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.5/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.5/distutils/command/build_ext.py", line 338, in run
        self.build_extensions()
      File "/tmp/pip-build-7wgfk62t/Pillow/setup.py", line 516, in build_extensions
        (f, f))
    ValueError: jpeg is required unless explicitly disabled using --disable-jpeg, aborting
    
    ----------------------------------------
  Rolling back uninstall of Pillow
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-7wgfk62t/Pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-7y9wo3n8-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-7wgfk62t/Pillow/

**Comment by bogdan-telenav** [comment]
@gzin can you send me some samples of images maybe with a dropbox link or something like this. I would like to help with this.

**Comment by james2432** [comment]
Pillow isnt compiling because it's missing jpg support. Trt installing this, should fix the pillow issue:
sudo apt-get install libtiff5-dev libjpeg8-dev zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev python-tk

**Comment by gzin** [comment]
@james2432 perfect!!!
```
Successfully built Pillow
Installing collected packages: Pillow, rauth, django, image
  Found existing installation: Pillow 3.1.2
    Uninstalling Pillow-3.1.2:
      Successfully uninstalled Pillow-3.1.2
```
But then, when I run the script:
```
For login go to this URL in your browser:
http://www.openstreetmap.org/oauth/authorize?oauth_token=...
Login and  grant acces then press ENTER

No sequence file existing
Found 562 pictures to upload
Expecting value: line 1 column 1 (char 0)
Uploaded error
Expecting value: line 1 column 1 (char 0)
Uploaded error
Expecting value: line 1 column 1 (char 0)
Uploaded error
Expecting value: line 1 column 1 (char 0)
Uploaded error
Expecting value: line 1 column 1 (char 0)
Uploaded error
Expecting value: line 1 column 1 (char 0)
Uploaded error
Expecting value: line 1 column 1 (char 0)
Uploaded error
```
Do I need a sequence file? How can I create it?
What else goes wrong?

**Comment by james2432** [comment]
Do you have write access to those photo folders? It's like it cant create the sequence file in the folder or write to it

**Comment by gzin** [comment]
This time I started the script with root privileges. Yes write is possible.

Now I've seen, that there are files created:

sequence_file.txt (last changed on Oct 5th; perhaps with the java gui):
`   -1`

count_file.txt (last changed on Oct 6th; with the script)
```
1516
17
18
19
20
21
...
72
73
74
75
```

**Comment by bogdan-telenav** [comment]
@gzin i checked your photos  and i recommend  the following steps for python upload scripts and i have for test python 3.5.1:
1. install requirements from : https://github.com/openstreetview/upload-scripts/blob/master/upload_photos_by_exif/requirements.txt with this versions.
2. clean the folder where you have the images(delete sequence_id.txt and count_file.txt)
3. try again with this environment.

If after this steps you still have some problems let me know here on on emal bogdan.racasan@telenav.com 

Thanks for helping 👍

**Comment by gzin** [comment]
I deleted the 2 status files and started the script again and...

```
No sequence file existing
Found 562 pictures to upload
processing 2016_09_10_09_33_02_913.jpg
Uploaded - 1 of total :562, percentage: 0.18%
processing 2016_09_10_09_33_04_197.jpg
Uploaded - 2 of total :562, percentage: 0.36%
...
Uploaded - 560 of total :562, percentage: 99.64%
processing 2016_09_10_09_42_39_982.jpg
Uploaded - 561 of total :562, percentage: 99.82%
processing 2016_09_10_09_42_38_326.jpg
Uploaded - 562 of total :562, percentage: 100.0%
Finish uploading form dir: ..../2016_09_10_07_33_01_018/ with sequence id: 24470
```

Perfect!
Thank you very much!!

**Comment by bogdan-telenav** [comment]
I'm glad that i can help you 👍
