### ISSUE TITLE
I want to upload pics from computer

### ISSUE THREAD

**Issue by yopaseopor** [openstreetview/openstreetview.org#9]
Hi. 
I like open source, and also like street view projects. I have some street view pics (160ks) so I want to upload via web (via app I have tried...and I have failed). Will be this possible?

**Comment by james2432** [comment]
in beta they had python scripts to upload such files, and they were working on a GUI application. I'm sure they will make it available soon.

**Comment by bogdans-telenav** [comment]
@yopaseopor as @james2432 said we have some scripts for doing exactly this also we are working on a GUI and they will be public in a few days.
@james2432 thanks for your answers.

**Comment by martijnv-telenav** [comment]
duplicate of #7
