### ISSUE TITLE
Tracks stuck in "Processing"

### ISSUE THREAD

**Issue by nikolajsheller** [openstreetview/openstreetview.org#93]
I have 6 tracks that have been stuck in "PROCESSING" for 4 days.
Is there a problem, or can I expect more than 4 days to elapse?

**Comment by ToeBee** [comment]
The servers that process uploaded sequences have been overloaded for weeks. @martijnv-telenav said they recently added more servers so it should hopefully start catching up. If my sequences are any indication, it is currently processing uploads from late November. Some I uploaded on November 23rd are processed but ones from November 29th and all more recent uploads are still stuck in processing.

**Comment by nikolajsheller** [comment]
Thank you for the information.
I will close th issue, and eagerly await for my traces to be processed.
